-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 21:04:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema analyses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analyses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analyses` DEFAULT CHARACTER SET utf8 ;
USE `analyses` ;

-- -----------------------------------------------------
-- Table `analyses`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyses`.`users` (
  `id` INT(10) NOT NULL,
  `name` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `password` VARCHAR(191) NULL,
  `type` TINYINT(4) NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyses`.`procedures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyses`.`procedures` (
  `id` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  `price` DECIMAL(10,2) NULL,
  `user_id` INT NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `analyses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `analyses`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analyses`.`tests` (
  `id` INT(10) NOT NULL,
  `user_id` INT(10) NULL,
  `procedure_id` INT(10) NULL,
  `date` DATE NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `procedure_id_idx` (`procedure_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `analyses`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `procedure_id`
    FOREIGN KEY (`procedure_id`)
    REFERENCES `analyses`.`procedures` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'sistemaweb' IDENTIFIED BY '123456';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
